{
 "title": "Loki Visual Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Access Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server Portocol",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (server_protocol) (count_over_time(  \n{namespace=\"nginx-ingress\"} | json | logtype=\"accesslog\" | json\n|  server_protocol!= \"\" and  server_protocol!= \"-\" | __error__=\"\" [15m]))",
     "legendFormat": "{{ server_protocol }}"
    }
   ]
  },
  {
   "title": "HTTP Status",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time(  \n{namespace=\"nginx-ingress\"} | json | logtype=\"accesslog\" | json\n|  status!= \"\" and  status!= \"-\" | __error__=\"\" [15m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Top 10 ServerName",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (server_name) (count_over_time(  \n{namespace=\"nginx-ingress\"} | json | logtype=\"accesslog\" | json\n|  server_name!= \"\" and  server_name!= \"-\" | __error__=\"\" [15m])))",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Top 10 UserAgent",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (http_user_agent) (count_over_time(  \n{namespace=\"nginx-ingress\"} | json | logtype=\"accesslog\" | json\n|  http_user_agent!= \"\" and  http_user_agent!= \"-\" | __error__=\"\" [15m])))",
     "legendFormat": "{{http_user_agent}}"
    }
   ]
  },
  { "title": "Security Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Outcome Passed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (outcome) (count_over_time( \n{namespace=\"nginx-ingress\"} | json | logtype=\"securitylog\" | json\n|  outcome=\"PASSED\" [15m])))"
    }
   ]
  },
  {
   "title": "Outcome ALERTED",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (outcome) (count_over_time( \n{namespace=\"nginx-ingress\"} | json | logtype=\"securitylog\" | json\n|  outcome=\"ALERTED\" [15m])))"
    }
   ]
  },
  {
   "title": "Outcome REJECTED",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (outcome) (count_over_time(  \n{namespace=\"nginx-ingress\"} | json | logtype=\"securitylog\" | json\n|  outcome=\"REJECTED\" [15m])))"
    }
   ]
  },
  {
   "title": "Outcome Reason",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (outcome_reason) (count_over_time( \n{namespace=\"nginx-ingress\"} | json | logtype=\"securitylog\" | json\n|  outcome_reason!= \"\" and  outcome_reason!= \"-\" | __error__=\"\" [15m])))",
     "legendFormat": "{{outcome_reason}}"
    }
   ]
  },
  {
   "title": "Top10 Violations",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (violations) (count_over_time(  \n{namespace=\"nginx-ingress\"} | json | logtype=\"securitylog\" | json\n|  violations!= \"\" and  violations!= \"-\" | __error__=\"\" [15m])))",
     "legendFormat": "{{violations}}"
    }
   ]
  },
  {
   "title": "Severity",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (severity) (count_over_time( \n{namespace=\"nginx-ingress\"} | json | logtype=\"securitylog\" | json\n|  severity!= \"\" and  severity!= \"-\" | __error__=\"\" [15m])))",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Viol Rate",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (violation_rating) (count_over_time( \n{namespace=\"nginx-ingress\"} | json | logtype=\"securitylog\" | json\n|  violation_rating!= \"\" and  violation_rating!= \"-\" | __error__=\"\" [15m])))",
     "legendFormat": "{{violation_rating}}"
    }
   ]
  },
  {
   "title": "Top10 Sig Names",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (sig_names) (count_over_time( \n{namespace=\"nginx-ingress\"} | json | logtype=\"securitylog\" | json\n|  sig_names!= \"\" and  sig_names!= \"-\" | __error__=\"\" [15m])))",
     "legendFormat": "{{sig_names}}"
    }
   ]
  },
  {
   "title": "Top10 Sig IDs",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (sig_ids) (count_over_time(  \n{namespace=\"nginx-ingress\"} | json | logtype=\"securitylog\" | json\n|  sig_ids!= \"\" and  sig_ids!= \"-\" | __error__=\"\" [15m])))",
     "legendFormat": "{{ sig_ids }}"
    }
   ]
  },
  {
   "title": "Top10 Sig Cves",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (sig_cves) (count_over_time(\n{namespace=\"nginx-ingress\"} | json | logtype=\"securitylog\" | json\n|  sig_cves!= \"\" and sig_cves!= \"-\" and sig_cves!~ \",+\"  | __error__=\"\" [15m])))",
     "legendFormat": "{{ sig_cves }}"
    }
   ]
  },
  { "title": "Bot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Top 10 Bot Cat",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (bot_category) (count_over_time( \n{namespace=\"nginx-ingress\"} | json | logtype=\"securitylog\" | json\n|  bot_category!= \"\" and  bot_category!= \"-\" | __error__=\"\" [15m])))",
     "legendFormat": "{{ bot_category }}"
    }
   ]
  },
  {
   "title": "Top 10 Bot Sig",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (bot_signature_name) (count_over_time(  \n{namespace=\"nginx-ingress\"} | json | logtype=\"securitylog\" | json\n|  bot_signature_name!= \"\" and  bot_signature_name!= \"-\" | __error__=\"\" [15m])))",
     "legendFormat": "{{ bot_signature_name }}"
    }
   ]
  },
  {
   "title": "Top 10 Bot Class",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (client_class) (count_over_time(  \n{namespace=\"nginx-ingress\"} | json | logtype=\"securitylog\" | json\n|  client_class!= \"\" and  client_class!= \"-\" | __error__=\"\" [15m])))",
     "legendFormat": "{{ client_class }}"
    }
   ]
  },
  { "title": "Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "NIC Access Log",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "{namespace=\"nginx-ingress\"} | json | logtype=\"accesslog\" | json"
    }
   ]
  },
  {
   "title": "NIC Security Log",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "{namespace=\"nginx-ingress\"} | json | logtype=\"securitylog\" | json"
    }
   ]
  },
  {
   "title": "NSM SideCar Log",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "{container=\"nginx-mesh-sidecar\"} | json | line_format \"{{.log}}\" "
    }
   ]
  },
  {
   "title": "NSM System Log",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "{namespace=\"nginx-mesh\"} | json | line_format \"{{.log}}\" "
    }
   ]
  }
 ]
}