{
 "title": "NGINX Plus Ingress Controller",
 "description": "A rich collection of Prometheus metrics from NGINX Plus Kubernetes Ingress Controller",
 "tags": [
  "nginx",
  "plus",
  "ingress"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "NIC",
    "query": {
     "query": "label_values(nginx_ingress_controller_ingress_resources_total, app) "
    }
   }
  ]
 },
 "panels": [
  { "title": "Environment Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NGINX Plus Reload",
   "type": "stat",
   "description": "Status of the last NGINX Plus reload.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_nginx_last_reload_status{app=\"$NIC\"})"
    }
   ]
  },
  {
   "title": "Reloads",
   "type": "stat",
   "description": "Number of successful NGINX Plus reloads.",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_nginx_reloads_total{app=\"$NIC\"})"
    }
   ]
  },
  {
   "title": "Reload Errors",
   "type": "stat",
   "description": "Number of unsuccessful NGINX Plus reloads.",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_nginx_reload_errors_total{app=\"$NIC\"})"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "description": "Bytes received from clients and sent to clients.",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_nginxplus_server_zone_received{app=\"$NIC\"}[5m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(irate(nginx_ingress_nginxplus_server_zone_sent{app=\"$NIC\"}[5m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Last Reload Time",
   "type": "stat",
   "description": "Last controller reload milliseconds.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_nginx_last_reload_milliseconds{app=\"$NIC\"})"
    }
   ]
  },
  { "title": "Ingress Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "HTTP Request Volume",
   "type": "stat",
   "description": "Total http requests per second looking back over the last 5 minutes.",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_nginxplus_http_requests_total{app=\"$NIC\"}[5m]))"
    }
   ]
  },
  {
   "title": "Ingress State",
   "type": "stat",
   "description": "Current State of the NGINX Ingress Controller.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "nginx_ingress_nginxplus_up{}", "legendFormat": "{{app}}" }
   ]
  },
  {
   "title": "Zone Request Volume",
   "type": "stat",
   "description": "Total http requests per second looking back over the last 5 minutes across all server zones.",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum( irate(  nginx_ingress_nginxplus_server_zone_requests{app=\"$NIC\"}[5m])) ",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Count",
   "type": "stat",
   "description": "Total number of deployed Ingress .",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_ingress_resources_total{app=\"$NIC\"})"
    }
   ]
  },
  {
   "title": "Success Rates Over Time",
   "type": "graph",
   "description": " 1|2|3xx response status codes.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_nginxplus_server_zone_responses{code=\"1xx\",app=\"$NIC\"}[5m])) ",
     "legendFormat": "1xx"
    },
    {
     "expr": "sum(irate(nginx_ingress_nginxplus_server_zone_responses{code=\"2xx\",app=\"$NIC\"}[5m])) ",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(irate(nginx_ingress_nginxplus_server_zone_responses{code=\"3xx\",app=\"$NIC\"}[5m])) ",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(irate(nginx_ingress_nginxplus_server_zone_responses{code=\"4xx\",app=\"$NIC\"}[5m])) ",
     "legendFormat": "4xx"
    }
   ]
  },
  {
   "title": "Error Rates Over Time",
   "type": "graph",
   "description": " 4|5xx response status codes.",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_nginxplus_server_zone_responses{code=~\"[4].*\",app=\"$NIC\"}[2m]))",
     "legendFormat": "Client Errors"
    },
    {
     "expr": "sum(rate(nginx_ingress_nginxplus_server_zone_responses{code=~\"[5].*\",app=\"$NIC\"}[2m]))",
     "legendFormat": "Server Errors"
    }
   ]
  },
  {
   "title": "Virtual Server",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_virtualserver_resources_total{app=\"$NIC\"})",
     "legendFormat": "Virtual Server"
    },
    {
     "expr": "sum(nginx_ingress_controller_virtualserverroute_resources_total{app=\"$NIC\"})",
     "legendFormat": "Virtual Server Router"
    },
    {
     "expr": "sum(nginx_ingress_controller_transportserver_resources_total{app=\"$NIC\"})",
     "legendFormat": "Transport Server"
    }
   ]
  },
  {
   "title": "Request Success Rate",
   "type": "stat",
   "description": "Non-4|5xx response status codes divided by total number of response status codes.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate( nginx_ingress_nginxplus_server_zone_responses{code!~\"[4-5].*\",app=\"$NIC\"}[5m])) / sum(rate(nginx_ingress_nginxplus_server_zone_responses{app=\"$NIC\"}[5m]))"
    }
   ]
  },
  { "title": "Upstream Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Upstream Success Rate",
   "type": "graph",
   "description": "Upstream success rate Over Time.",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_nginxplus_server_zone_responses{app=\"$NIC\"} [5m])) by (code,server_zone)\r\n"
    }
   ]
  },
  {
   "title": "Service Count",
   "type": "stat",
   "description": "Total number of service count",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nginx_ingress_nginxplus_upstream_server_state{app=\"$NIC\"} ",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Upstream Error Rate",
   "type": "graph",
   "description": " 4|5xx Status Codes",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_nginxplus_server_zone_responses{app=\"$NIC\", code=~\"[4].*\"} [5m])) by (code,server_zone)",
     "legendFormat": "Client Errors"
    },
    {
     "expr": "sum(rate(nginx_ingress_nginxplus_server_zone_responses{app=\"$NIC\", code=~\"[5].*\"} [5m])) by (code,server_zone)",
     "legendFormat": "Server Errors"
    }
   ]
  },
  { "title": "SSL Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "SSL Performance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_ingress_nginxplus_ssl_handshakes{app=\"$NIC\"}[5m])",
     "legendFormat": "{{instance}} Handshakes"
    },
    {
     "expr": "irate(nginx_ingress_nginxplus_ssl_handshakes_failed{app=\"$NIC\"}[5m])",
     "legendFormat": "{{instance}} Failed"
    },
    {
     "expr": "irate(nginx_ingress_nginxplus_ssl_sessions_reuses{app=\"$NIC\"}[5m])",
     "legendFormat": "{{instance}} Reuses"
    }
   ]
  }
 ]
}