{
 "title": "NGINX Mesh Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "GLOBAL SUCCESS RATE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(nginxplus_upstream_server_responses{job=\"nginx-mesh-sidecars\",code=~\"1xx|2xx\"}[5m])) / sum(irate(nginxplus_upstream_server_responses{job=\"nginx-mesh-sidecars\"}[5m]))"
    }
   ]
  },
  {
   "title": "GLOBAL REQUEST VOLUME",
   "type": "stat",
   "gridPos": { "h": 6, "w": 13, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(nginxplus_http_requests_total{job=\"nginx-mesh-sidecars\"}[5m]))"
    }
   ]
  },
  {
   "title": "PODS MONITORED",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nginxplus_http_requests_total{job=\"nginx-mesh-sidecars\"})"
    }
   ]
  },
  {
   "title": "Request Volume",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(nginxplus_http_requests_total{job=\"nginx-mesh-sidecars\"}[5m])"
    }
   ]
  },
  {
   "title": "Pod Success",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginxplus_upstream_server_responses{job=\"nginx-mesh-sidecars\",code=~\"1xx|2xx\"}[5m])) by (app, version) / sum(irate(nginxplus_upstream_server_responses{job=\"nginx-mesh-sidecars\"}[5m])) by (app, version)"
    }
   ]
  },
  {
   "title": "Sidecar Memory Usage (RSS)",
   "type": "graph",
   "description": "RSS used by NGINX Service Mesh sidecars",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nginxplus_workers_mem_rss{job=\"nginx-mesh-sidecars\"}"
    }
   ]
  },
  {
   "title": "Sidecar Memory Usage (Private)",
   "type": "graph",
   "description": "Private memory used by NGINX Service Mesh sidecars",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginxplus_workers_mem_private{job=\"nginx-mesh-sidecars\"}"
    }
   ]
  }
 ]
}